#!/bin/bash

git clone https://github.com/computermouth/qemu-static-conf.git
mkdir -p /lib/binfmt.d
cp qemu-static-conf/*.conf /lib/binfmt.d/
service systemd-binfmt restart

apt-get update
apt-get install -y qemu-user-static
